server {
    listen 80;
    server_name webhook.cursala.com.ar;

    # Carpeta compartida interna para que Let's Encrypt verifique que el dominio es tuyo
    location /.well-known/acme-challenge/ {
        root /etc/nginx/conf.d;
    }

    # El resto del tráfico temporalmente va al bot en HTTP
    location / {
        proxy_pass http://whatsapp-bot:8080;
        proxy_set_header Host $host;
    }
}
